# Site settings
title: Leiyu
email: yourlin127@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   前端博客
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:  leiyu
github_username:  yourlei

# Build settings
markdown: kramdown
